CREATE TABLE MEMBER(
	ID			NVARCHAR2(10) NOT NULL ,
	PASS		NVARCHAR2(10) NOT NULL,
	NAME		NVARCHAR2(30) NOT NULL,
	REGIDATE	DATE DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY(ID)
	);
	
CREATE TABLE BOARD(
	NUM			NUMBER PRIMARY KEY,
	TITLE		NVARCHAR2(200) NOT NULL,
	CONTENT		NVARCHAR2(2000) NOT NULL,
	ID			NVARCHAR2(10)	NOT NULL,
	POSTDATE	DATE DEFAULT SYSDATE NOT NULL,
	VISITCOUNT	NUMBER(6));
	
ALTER TABLE BOARD ADD CONSTRAINT BOARD_MEM_FK FOREIGN KEY (ID) REFERENCES MEMBER (ID) ;

CREATE SEQUENCE SEQ_BOARD_NUM
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;

INSERT INTO MEMBER(ID, PASS, NAME) VALUES('kkw', '1234', '김기원');
INSERT INTO MEMBER(ID, PASS, NAME) VALUES('qqq', '1111', '김김김');
INSERT INTO MEMBER(ID, PASS, NAME) VALUES('www', '2222', '이이이');
INSERT INTO MEMBER(ID, PASS, NAME) VALUES('eee', '3333', '박박박');
INSERT INTO MEMBER(ID, PASS, NAME) VALUES('rrr', '4444', '나나나');
INSERT INTO BOARD VALUES(SEQ_BOARD_NUM.NEXTVAL, '제목1', '내용1', 'kkw', SYSDATE, 0);
INSERT INTO BOARD VALUES(SEQ_BOARD_NUM.NEXTVAL, '제목2', '내용2', 'qqq', SYSDATE, 0);
INSERT INTO BOARD VALUES(SEQ_BOARD_NUM.NEXTVAL, '제목3', '내용3', 'www', SYSDATE, 0);
INSERT INTO BOARD VALUES(SEQ_BOARD_NUM.NEXTVAL, '제목4', '내용4', 'eee', SYSDATE, 0);
INSERT INTO BOARD VALUES(SEQ_BOARD_NUM.NEXTVAL, '제목5', '내용5', 'rrr', SYSDATE, 0);

SELECT * FROM MEMBER;
SELECT * FROM BOARD;






